# app/exceptions.py
class DatabaseError(Exception):
    pass
